---
title: 异步线程事务管理
date: 2024-05-20 11:40:03
tags: 框架
categories: 框架
---

### 线程事务管理

### 异步线程事务管理

#### 1、实现异步线程事务管理

spring事务管理中，如果在主线程中创建异步线程去执行数据库更新操作，那么当子线程抛出异常时，主线程是无法感知的，也就是无法对异步线程中的事务进行管理。

则会出现下面两种问题：（注，都在执行数据插入成功之后抛出异常）

- 子线程抛出异常，数据库中既有主线程插入的数据也有子线程插入的数据。
- 主线程抛出异常，数据库中只有子线程插入的数据。

**此刻只有主线程有事务管理，而子线程没有，因为主线程的事务是管理不到子线程的，所以无论主线程还是子线程抛出异常，子线程的数据都不会回滚。**

```java
@Transactional
public void test() throws InterruptedException {
    TestPojo testPojo = new TestPojo( "1", "1");
    int res = testMapper.insertData(testPojo);
    Thread thread = new Thread(new Runnable() {
        @Override
        public void run() {
            TestPojo testPojo = new TestPojo( "2", "2");
            int cnt = testMapper.insertData(testPojo);
            System.out.println("子线程 执行结果：" + cnt);
        }
    });
    thread.start();
    thread.join();
    System.out.println("主线程 执行结果：" + res);
    int b = 1/0;
}
```

执行上述代码，数据库中只有子线程插入成功的数据。

```java
@Transactional
public void test() throws InterruptedException {
    TestPojo testPojo = new TestPojo( "1", "1");
    int res = testMapper.insertData(testPojo);
    Thread thread = new Thread(new Runnable() {
        @Override
        public void run() {
            TestPojo testPojo = new TestPojo( "2", "2");
            int cnt = testMapper.insertData(testPojo);
            System.out.println("子线程 执行结果：" + cnt);
            int b = 1/0;
        }
    });
    thread.start();
    thread.join();
    System.out.println("主线程 执行结果：" + res);
}
```

执行上述代码主线程和子线程的数据都插入成功，因为子线程是没有事务管理的。

#### 2、解决问题

在spring事务管理中，如果执行事务管理的代码，每个线程拥有的数据库连接都是不一样，而数据库连接都不一样了，自然就实现了事务的隔离，不相关线程的事务，自然是一样的。

而spring的事务传播机制，则会在获取数据数据库连接之前进行判断，如果事务传播机制是复用事务，那么则会拿到父线程的数据库连接，从而达到复用的事务的功能。

**那么如果让子线程的数据库连接和主线程的数据库连接使用同一个是不是就能够解决异步线程的事务管理问题呢。**

代码如下：

```java
@Transactional
public void test() throws InterruptedException {
    TestPojo testPojo = new TestPojo( "1", "1");
    int res = testMapper.insertData(testPojo);
    // 拿到主线程的数据库连接对象
    ConnectionHolder conHolder = (ConnectionHolder) TransactionSynchronizationManager.getResource(dataSource);
    Thread thread = new Thread(new Runnable() {
        @Override
        public void run() {
            // 执行sql前绑定主线程的数据库连接对象。
            TransactionSynchronizationManager.bindResource(dataSource,conHolder);
            TestPojo testPojo = new TestPojo( "2", "2");
            int cnt = testMapper.insertData(testPojo);
            System.out.println("子线程 执行结果：" + cnt);
            // 使用完后进行解绑。
            TransactionSynchronizationManager.unbindResource(dataSource);
        }
    });
    int b = 1/0;
    thread.start();
    thread.join();
    System.out.println("父线程 执行结果：" + res);
}
```

执行上述代码，会发现主线程的数据和子线程的数据都没插入成功。

那么如果此刻把异常放在子线程中，会是什么结果呢！

```java
@Transactional
public void test() throws InterruptedException {
    TestPojo testPojo = new TestPojo( "1", "1");
    int res = testMapper.insertData(testPojo);
    // 拿到主线程的数据库连接对象
    ConnectionHolder conHolder = (ConnectionHolder) TransactionSynchronizationManager.getResource(dataSource);
    Thread thread = new Thread(new Runnable() {
        @Override
        public void run() {
            // 执行sql前绑定主线程的数据库连接对象。
            TransactionSynchronizationManager.bindResource(dataSource,conHolder);
            TestPojo testPojo = new TestPojo( "2", "2");
            int cnt = testMapper.insertData(testPojo);
            System.out.println("子线程 执行结果：" + cnt);
            // 使用完后进行解绑。
            TransactionSynchronizationManager.unbindResource(dataSource);
            int b = 1/0;
        }
    });
    thread.start();
    thread.join();
    System.out.println("父线程 执行结果：" + res);
}
```

执行结果为：主线程和子线程的数据都成功插入数据库了，并没有发生回滚操作。

**这种情况，不应该主线程提交成功，而子线程抛出异常进行回滚吗？为什么子线程没有执行回滚操作呢！**

此刻子线程只是数据库连接池跟主线程相同，但是子线程中并没有事务管理器，也就是没有捕获异常后对代码进行回滚功能。此刻也只有主线程有事务管理器。上面为什么能都回滚成功呢！是因为主线程中抛出的异常被事务管理器给捕获了，并对数据库连接池进行回滚，而此刻的子线程又是使用的相同的数据库连接池，所以数据都能进行回滚操作。

那如何让主线程中的事务管理器感知到子线程中的异常呢！可以通过Thread类中的方法。具体代码如下。

```java
@Transactional
public void test() throws InterruptedException {
    TestPojo testPojo = new TestPojo( "1", "1");
    int res = testMapper.insertData(testPojo);
    // 拿到主线程的数据库连接对象
    ConnectionHolder conHolder = (ConnectionHolder) TransactionSynchronizationManager.getResource(dataSource);
    Thread thread = new Thread(new Runnable() {
        @Override
        public void run() {
            // 执行sql前绑定主线程的数据库连接对象。
            TransactionSynchronizationManager.bindResource(dataSource,conHolder);
            TestPojo testPojo = new TestPojo( "2", "2");
            int cnt = testMapper.insertData(testPojo);
            System.out.println("子线程 执行结果：" + cnt);
            // 使用完后进行解绑。
            TransactionSynchronizationManager.unbindResource(dataSource);
            int b = 1/0;
        }
    });
    final Throwable[] a = new Throwable[1];
    // 设置子线程抛出异常的处理器
    thread.setUncaughtExceptionHandler(new Thread.UncaughtExceptionHandler() {
        @Override
        public void uncaughtException(Thread t, Throwable e) {
            a[0] = e;
        }
    });
    int b = 1/0;
    thread.start();
    thread.join();
    // 如果不等于null 则子线程中有异常，直接抛出，这样spring的事务管理器就能捕获并回滚。
    if(a[0] != null ){
        throw new RuntimeException(a[0]);
    }
    System.out.println("父线程 执行结果：" + res);
}
```

参考视频：https://www.bilibili.com/video/BV1tV411V77h/?spm_id_from=333.999.0.0